### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'scheme'  in python2.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mettienne/pysimplesoap#53]
```
client.py

# The current code is only working with Python 2.5+
#o = urlparse(url)
# work for python2.4+
url_scheme, netloc, path, query, fragment = urlsplit(url)
if not url_scheme in ('http','https', 'file'):
```

Original issue reported on code.google.com by `jinyinq...@gmail.com` on 10 Feb 2012 at 4:25
